import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          Header
        </header>
        <main>
          {children}
        </main>
        <footer>
          <p>Footer content goes here</p>
        </footer>
      </body>
    </html>
  )
}
